### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by clarkdo** [Magic-Academy/.github#121]
### Name

Clark

### Discord Username (if applicable)

Clark#2260

### Additional Context

I am very interested in open source projects and am already a member of some open source organizations. I hope to join Magic-Academy open source and more engineers to discuss technology and contribute to open source projects.

**Comment by songdaochuanshu** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/Magic-Academy/people<br>
