### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by TheCleverIdiott** [Magic-Academy/.github#183]
### Name

Aritra Ghosh

### Discord Username (if applicable)

TheCleverIdiot#8139

### Additional Context

I learnt about this community through a friend.

I am deeply passionate about technology. Becoming a member would allow me to work on cutting-edge projects, collaborate with like-minded individuals and further develop my skills in this field. I am excited about the prospect of being part of a supportive community that fosters continuous learning and growth. I believe that being
part of this community will provide me with valuable networking opportunities, help
me build meaningful connections and expand my professional network. I also believe that it'll help me to connect with others, with whom we can learn together, and grow together. I also seriously believe that it'll help me to contribute to projects that a lot of people will use hence affecting lives positively which is the true essence of open-sourcing.

**Comment by songdaochuanshu** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/Magic-Academy/people<br>

**Comment by songdaochuanshu** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/G2jgHeQfy4">Discord Server</a> and our <a href="https://github.com/Magic-Academy">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>
