### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by uchiha5555** [Magic-Academy/.github#218]
### Name

Austin Axtell

### Discord Username (if applicable)

uchiha.clan5555

### Additional Context

Hello everyone, I am Austin 👋
I hope to join this GitHub Org of writers and developers! My goal is to share my experiences and learn from others, so we can all grow together. Here's a bit more about me:

👨‍💻 I work as a Frontend Developer, which I love because it allows me to solve real-world problems with technology.
📚 I'm passionate about learning new things. Whether it's a new programming language or a cooking recipe, I enjoy the challenge of picking up new skills.
🤝 I believe in collaboration and teamwork. I think the best ideas come from diverse perspectives, so I'm eager to hear what everyone has to say.
Thanks for reading, and please don't hesitate to reach out if you want to chat or collaborate on a project!

**Comment by songdaochuanshu** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/Magic-Academy/people<br>

**Comment by songdaochuanshu** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/G2jgHeQfy4">Discord Server</a> and our <a href="https://github.com/Magic-Academy">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>
