### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by tayyab-ilyas** [Magic-Academy/.github#254]
### Name

Tayyab

### Discord Username (if applicable)

tayyab9594

### Additional Context

I'm attracted to Magic Academy for its open-source values and collaborative spirit. The emphasis on respectful communication and equal learning appeals to my tech enthusiasm.

**Comment by songdaochuanshu** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/Magic-Academy/people<br>
