### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by shiny0110** [Magic-Academy/.github#255]
### Name

Saad Jabri

### Discord Username (if applicable)

saad0713

### Additional Context

I've always been a firm believer in the power of open-source and the value of collaborative contributions in the tech domain. The Magic Academy's core principles resonate deeply with me, particularly the emphasis on respect for everyone's contribution, advocacy for fair communication, and encouragement for sharing and learning. The idea that no matter where one stands in their tech journey, from novices to seasoned professionals, all are welcome, truly speaks to the inclusivity I've been looking for in a tech community.

Additionally, the strong adherence to the code of conduct and the respect for original works within the community highlights a sense of integrity that aligns with my personal values. I've always wanted to be part of a community where everyone can freely discuss, ask, and share without hesitation. The Magic Academy seems like an environment where I can both contribute my knowledge and gain insights from others, fostering mutual growth.

I'm eager to collaborate with like-minded individuals, share my experiences, learn from theirs, and together create something meaningful in the tech world. I believe that by joining the Magic Academy, I'll not only enhance my skills and understanding but also contribute to the overarching mission of furthering technology through collective efforts.

**Comment by songdaochuanshu** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/G2jgHeQfy4">Discord Server</a> and our <a href="https://github.com/Magic-Academy">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>

**Comment by songdaochuanshu** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/Magic-Academy/people<br>
