### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by usengun** [Magic-Academy/.github#257]
### Name

Utkucan

### Discord Username (if applicable)

utkucan_

### Additional Context

What I appreciate most about the Magic Academy community is their commitment to fostering a culture of continuous learning and growth. I've been following their discussions and resources, and it's evident that the members are not only passionate about their craft but also eager to share knowledge and support one another. Additionally, the diversity of topics covered, from cutting-edge testing methodologies to emerging technologies, aligns perfectly with my career aspirations.

I'm excited about the prospect of joining the Magic Academy community for several reasons. Firstly, I believe that being part of such a vibrant and knowledgeable community will provide me with invaluable insights and perspectives that can enhance my skills as a software tester. Secondly, I'm eager to contribute to the community by sharing my own experiences and insights, thus giving back to the testing community that has been so instrumental in my career development. Lastly, I see the Magic Academy as a place where I can stay up-to-date with the latest industry trends and innovations, which will help me excel in my current role and future endeavors.

**Comment by songdaochuanshu** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/Magic-Academy/people<br>

**Comment by songdaochuanshu** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/G2jgHeQfy4">Discord Server</a> and our <a href="https://github.com/Magic-Academy">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>
