### ISSUE TITLE
Update new member

### ISSUE THREAD

**Issue by wizard0918** [Magic-Academy/.github#358]
### What would you like to share?

Update new member
https://github.com/wizard0918

### Additional information

If you assign this update to me, I am really happy and will update asap.
Thanks

**Comment by songdaochuanshu** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/G2jgHeQfy4">Discord Server</a> and our <a href="https://github.com/Magic-Academy">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>

**Comment by wizard0918** [comment]
I already join this git organization.
Hope to collaborate with you.
