### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by mujeebshk** [Magic-Academy/.github#380]
### Name

Mujeeb Shaik

### Additional Context

I want to join Magic-Academy because I see it as a place where I can grow both creatively and technically. The opportunity to connect with and learn from a diverse group of talented individuals excites me, as does the chance to participate in unique projects that blend art and technology. I am eager to contribute my own skills and ideas to the community, and I believe that being part of Magic-Academy will help me push the boundaries of my creative work while also gaining new insights and techniques.

**Comment by songdaochuanshu** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/Magic-Academy/people<br>

**Comment by songdaochuanshu** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/G2jgHeQfy4">Discord Server</a> and our <a href="https://github.com/Magic-Academy">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>
