### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by kentaurse** [Magic-Academy/.github#397]
### Name

Ethan Tan

### Discord Username (if applicable)

ethan_tan0212

### Additional Context

I specialize in blockchain development and website creation for businesses and individuals. I bring advanced skills to blockchain development, including expertise in smart contract creation, decentralized application (dApp) development, and blockchain architecture design. My experience spans various blockchain platforms such as Ethereum, Hyperledger, and Binance Smart Chain. Additionally, I possess a deep understanding of cryptographic principles, consensus algorithms, and security best practices in blockchain technology.

I am very interested in this project's development and believe it has great potential. I would like to contribute to its growth with my extensive experience and knowledge. If anyone has information on how I can join the development team and participate in this project, please let me know. Thank you.

**Comment by songdaochuanshu** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/Magic-Academy/people<br>

**Comment by songdaochuanshu** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/G2jgHeQfy4">Discord Server</a> and our <a href="https://github.com/Magic-Academy">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>
