### ISSUE TITLE
I would like to be part of this Magic-Academy!

### ISSUE THREAD

**Issue by sondosaabed** [Magic-Academy/.github#407]
### Name

Sondos 

### Additional Context

I came across your organization by github profiles. I would like to join this community because I love open source contribution and organizations

**Comment by songdaochuanshu** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/G2jgHeQfy4">Discord Server</a> and our <a href="https://github.com/Magic-Academy">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>
