### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Durgesh4993** [Magic-Academy/.github#408]
### Name

Durgesh Kumar Prajapati

### Discord Username (if applicable)

durgesh4993

### Additional Context

I am Durgesh Kumar Prajapati, Pre- Final year student of B.Tech (CSE). I am a full stack PHP & MERN Developer. And also worked as an Open Source Developer. As an Open Source Contributor I have contributed to XWiki, The Tor Project and Omega Up Organization.

**Comment by songdaochuanshu** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/Magic-Academy/people<br>

**Comment by songdaochuanshu** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/G2jgHeQfy4">Discord Server</a> and our <a href="https://github.com/Magic-Academy">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>
