### ISSUE TITLE
I'd love to get on board :3 

### ISSUE THREAD

**Issue by stinkyyyyy** [Magic-Academy/.github#411]
### Name

Hugo

### Discord Username (if applicable)

stinkyyyyyyyyy

### Additional Context

I was just looking into a developers profile as I usually do when I find an interesting open source project and I noticed that he only followed two people and one of them was your organization and I was just pretty curious about it so I clicked on your profile and I got excited because I have been playing with the idea of contributing to open source code for a while

**Comment by songdaochuanshu** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/Magic-Academy/people<br>

**Comment by songdaochuanshu** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/G2jgHeQfy4">Discord Server</a> and our <a href="https://github.com/Magic-Academy">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>
