### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Mubshr07** [Magic-Academy/.github#426]
### Name

Mubashir Iqbal

### Additional Context

As an AI expert and Qt C++ software developer, I specialize in Machine Learning, Natural Language Processing, and Advanced Text Analytics. I create robust systems for both desktop and embedded environments, leveraging tools like Apache Server, PHP, MySQL, HTML5, CSS3, Bootstrap, JavaScript, Django, and WordPress. Currently, I work in a government Electronics Research and Development department, focusing on designing, developing, and reverse-engineering electronic modules. I am passionate about continuous learning and innovation, always pushing the boundaries of what's possible in technology.👨🏻‍ 👨🏻‍💻

**Comment by songdaochuanshu** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/Magic-Academy/people<br>

**Comment by songdaochuanshu** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/G2jgHeQfy4">Discord Server</a> and our <a href="https://github.com/Magic-Academy">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>
