### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by MeetDOD** [Magic-Academy/.github#431]
### Name

Meet Dodiya

### Additional Context

I am a full stack developer and currently i am in my final year of engineering in information technology branch, I am also a open source contributor and found out your wonderfull community can't wait for my valuable contribution.

Thank You !

**Comment by songdaochuanshu** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/Magic-Academy/people<br>
