### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by albertoalejandro10** [Magic-Academy/.github#497]
### Name

Alberto Alejandro Núñez

### Discord Username (if applicable)

albertoalejandro10

### Additional Context

I was looking for an Open Source Community on GitHub and I find you. I want to contribute to open source and I think you could help me to do it.
I am a Developer with 3 years of experience. It would be nice to be part of Magic-Academy.

**Comment by songdaochuanshu** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/G2jgHeQfy4">Discord Server</a> and our <a href="https://github.com/Magic-Academy">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>

**Comment by songdaochuanshu** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/Magic-Academy/people<br>
