### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by rust-trust** [Magic-Academy/.github#503]
### Name

Elias

### Discord Username (if applicable)

tentwinkle1004

### Additional Context

**Summary:**
I am writing to express my interest in joining the Magic Academy. I believe my skills and experience in this organization can contribute to the ongoing projects and initiatives within your team.

**About Me:**
- **Experience:** I have over 4 years of experience in Blockchain and have worked on various DEX-related smart contracts.
- **Skills:** Solidity, Typescript, Rust, Subastrate, Ethereum, Solana, Foundry, Hardhat, V3/V4 DEXs.
- **GitHub Profile:** github.com/rust-trust

**Why I Want to Join:**
I am particularly excited about the work this team is doing in awesome project. I am eager to collaborate, learn, and contribute to specific projects or areas within the organization.

Thank you for considering my request. I look forward to the possibility of contributing to Magic Academy.

Best regards, 
Elias

**Comment by songdaochuanshu** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/Magic-Academy/people<br>

**Comment by songdaochuanshu** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/G2jgHeQfy4">Discord Server</a> and our <a href="https://github.com/Magic-Academy">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>
