### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by kingp08** [Magic-Academy/.github#550]
### Name

kingp08

### Discord Username (if applicable)

miracle_007

### Additional Context

I want to improve my skills in your community.

**Comment by songdaochuanshu** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/G2jgHeQfy4">Discord Server</a> and our <a href="https://github.com/Magic-Academy">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>

**Comment by kingp08** [comment]
Hi, @songdaochuanshu.
I've joined to your Discord server.
And what's next?

**Comment by songdaochuanshu** [comment]
> 你好，@songdaochuanshu。 我已加入您的 Discord 服务器。 下一步是什么？

 Dear kingp08,

      Thank you very much for your interest in joining the Magic-Academy community! We sincerely apologize for the delay in processing your request due to recent system updates.

      Your invitation to join the GitHub Organization has now been sent. Welcome to the community 🎉

      Please remember to accept the invitation and make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organization list and changing the dropdown to public:
      https://github.com/orgs/Magic-Academy/people

      Once again, we apologize for any inconvenience caused and appreciate your patience. If you have any questions or need further assistance, feel free to reach out.

      Best regards,
      The Magic-Academy Team
