### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by ymbtc757** [Magic-Academy/.github#556]
### Name

ymbtc757

### Discord Username (if applicable)

Yama

### Additional Context

Plz invite me

**Comment by songdaochuanshu** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/G2jgHeQfy4">Discord Server</a> and our <a href="https://github.com/Magic-Academy">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>

**Comment by ymbtc757** [comment]
Welcome to the community 🤓
If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our [Discord Server](https://discord.gg/G2jgHeQfy4) and our [GitHub Organisation](https://github.com/Magic-Academy) - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.

**Comment by ymbtc757** [comment]
> ### Name
> ymbtc757
> 
> ### Discord Username (if applicable)
> Yama
> 
> ### Additional Context
> Plz invite me
