### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Soumyadipgithub** [Magic-Academy/.github#567]
### Name

Soumyadip Giri

### Additional Context

I came across Magic-Academy while exploring various online communities focused on creativity and learning. What I love about this community is its emphasis on collaboration and sharing knowledge. It feels like a space where everyone can grow together, whether through magic, storytelling, or other creative pursuits. I want to join because I’m excited about the chance to connect with like-minded individuals, learn new skills, and contribute to the collective creativity. Plus, who doesn’t love a bit of magic in their life?

**Comment by songdaochuanshu** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/G2jgHeQfy4">Discord Server</a> and our <a href="https://github.com/Magic-Academy">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>
