### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by aadhi-i** [Magic-Academy/.github#588]
### Name

Adithya S Nair

### Discord Username (if applicable)

aadhi33_29319

### Additional Context

**Hello** , I am a newbie in the world of open source and I believe The Magic Academy will be a perfect place for me to get better guidance  and get my tech skills uplifted. I got to know about Magic Academy from Mr. Sanjay Viswanathan one of the mentors at GrilScript Summer of Code.

**Comment by songdaochuanshu** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/G2jgHeQfy4">Discord Server</a> and our <a href="https://github.com/Magic-Academy">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>

**Comment by aadhi-i** [comment]
Definitely, Thanks for the opportunity!
