### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [Magic-Academy/.github#600]
### Name

Rajdeep Chakraborty

### Discord Username (if applicable)

rootninja69

### Additional Context

I learned about this community while interacting with Contributors during the GSSoC 2024 Extended Program. I would love to be a part of this wonderful community and connect with similar minds.

**Comment by songdaochuanshu** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/G2jgHeQfy4">Discord Server</a> and our <a href="https://github.com/Magic-Academy">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>

**Comment by rajdeepchakraborty-rc** [comment]
Just came across this wonderful community and thought of joining it.

**Comment by rajdeepchakraborty-rc** [comment]
Will I receive the invite to this Organization later?
