### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by WednesdaySP** [Magic-Academy/.github#605]
### Name

Shashi Prabha

### Discord Username (if applicable)

Shashi Prabha | Contributor

### Additional Context

I discovered Magic Academy on GitHub and was immediately drawn to its core values of open-source collaboration and knowledge sharing. I love how the community emphasizes respect, equal communication, and creating a supportive environment for everyone, regardless of experience level. I’m excited to join because it offers the perfect space to learn, contribute, and grow alongside passionate tech enthusiasts while making meaningful contributions to open-source projects.

**Comment by songdaochuanshu** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/G2jgHeQfy4">Discord Server</a> and our <a href="https://github.com/Magic-Academy">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>
