### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by hamzathul** [Magic-Academy/.github#608]
### Name

Hamzathul Favas E

### Discord Username (if applicable)

hamzathul

### Additional Context

I am an aspiring MERN stack developer with a strong interest in open source contributions. I'm passionate about building web applications using MongoDB, Express, React, and Node.js, and I’m eager to collaborate with other developers. I’m also excited to learn new skills, explore different technologies, and grow as a developer alongside this community. I look forward to contributing and learning with everyone here.

**Comment by songdaochuanshu** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/G2jgHeQfy4">Discord Server</a> and our <a href="https://github.com/Magic-Academy">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>
