### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by shristirwt** [Magic-Academy/.github#611]
### Name

Shristi Rawat

### Discord Username (if applicable)

shristirawat_contributor

### Additional Context

I came to know about Magic-Academy through a maintainer of an open source project 
I liked the community's perspective of helping everyone grow together and providing them a collaborative environment
I am new to open source and it is a bit difficult to understand everything as a beginner. I want to join this community to learn more and grow with others

**Comment by songdaochuanshu** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/G2jgHeQfy4">Discord Server</a> and our <a href="https://github.com/Magic-Academy">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>
