### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by idimetrix** [Magic-Academy/.github#625]
### Name

Dmitry Selikhov

### Additional Context

I’m eager to join this community to expand my professional network and connect with like-minded individuals. I look forward to engaging, sharing insights, and learning from others to support both personal and collective growth.

**Comment by songdaochuanshu** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/G2jgHeQfy4">Discord Server</a> and our <a href="https://github.com/Magic-Academy">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>

**Comment by idimetrix** [comment]
@songdaochuanshu 

Do not see any invites yes. Can you double check?
