### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by RanitDERIA** [Magic-Academy/.github#626]
### Name

Ranit Deria

### Discord Username (if applicable)

ranitderia

### Additional Context

- I admire the collaborative and inclusive environment that the DEVs Dungeon community fosters. It’s inspiring to see developers come together to share knowledge, learn from each other, and work on open-source projects.
- I want to join this community to enhance my skills, contribute to exciting projects, and connect with like-minded individuals who are passionate about coding and technology. Being a part of this community would be a great opportunity to grow as a developer and help others along the way.

**Comment by songdaochuanshu** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/G2jgHeQfy4">Discord Server</a> and our <a href="https://github.com/Magic-Academy">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>
