### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Mehul2711** [Magic-Academy/.github#629]
### Name

Mehul Kumar

### Discord Username (if applicable)

mehul_27

### Additional Context

I came across Magic-Academy while searching for communities that focus on learning and growth in tech. I love how engaging and supportive everyone seems, and I appreciate the emphasis on skill development and collaboration. I want to join to learn new things, share ideas, and be part of a community that encourages creativity and progress.

**Comment by songdaochuanshu** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/G2jgHeQfy4">Discord Server</a> and our <a href="https://github.com/Magic-Academy">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>
