### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by idimetrix** [Magic-Academy/.github#637]
### Name

Dmitry Selikhov

### Discord Username (if applicable)

idimetrix

### Additional Context

I'm open source advocate and love to do open source contributions:

🚀CTO, 🏗️Software Architect, 🧑‍💻Technical Lead, 👨‍💼3X Founder. 🔗Linking companies with top tech talents.

CV: [https://dmitrii-selikhov.vercel.app](https://dmitrii-selikhov.vercel.app)
GitHub: [https://github.com/idimetrix](https://github.com/idimetrix)
LinkedIn: [https://www.linkedin.com/in/dimetrix](https://www.linkedin.com/in/dimetrix)

**Comment by songdaochuanshu** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/G2jgHeQfy4">Discord Server</a> and our <a href="https://github.com/Magic-Academy">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>
