### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by myselfshivams** [Magic-Academy/.github#643]
### Name

Shivam

### Additional Context

I’m excited to join the Magic Academy because it’s a community that values open-source, learning, and respect for everyone’s contributions. I love that it welcomes both beginners and experts, creating a space where we can learn and grow together. I want to be part of this group to improve my skills, contribute to projects, and connect with people who share my passion for tech.

**Comment by songdaochuanshu** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/G2jgHeQfy4">Discord Server</a> and our <a href="https://github.com/Magic-Academy">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>
